theme: jekyll-theme-hacker
markdown: GFM
title: Golden Notes - armanexplorer planet
description: A place to find the practical notes (mostly technically)

collections:
  jekyll:
    output: true
    permalink: /:collection/:name

defaults:
  # - scope:
  #     path: ""
  #     type: "authors"
  #   values:
  #     layout: "author"
  # - scope:
  #     path: ""
  #     type: "posts"
  #   values:
  #     layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"